---
title       : Workshop 1 - Next Generation Knowledge Forum
author      : 
framework   : shower        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
logo        : uoft.png
biglogo     : SI2013-Logo2.jpg
license: by-nc-sa
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
github      : {user: dirkchen, repo: kbsi13-pi}

--- .cover #Cover

# Embedded Assessment and Knowledge Building Analytics

### KBSI 2013 <br /> Puebla, Mexico, August 6, 2013

---

## Key issues in program

- group-directed sustained creative work with ideas
- Knowledge Forum interface design that makes knowledge building activity evident to students as the work proceeds
- parallel advances in basics, 21st century competencies and emergence of new competencies 
- metadiscourse—student discourse about ongoing knowledge-building discourse
- promisingness—students need help in reconstructing ideas at progressively higher levels

---

## A reinterpretation

- assess group-level processes
  - what should be assessed?
- interface design of analytics / integration into KF
  - how should KF analytics be integrated in KF?
  - how would it look like?
  - how to close the feedback loop?
- capture progresses?
- support "metadiscourse"---reconstruction of discourse
- support progressive development of ideas---promisingness

---

## Critical Next Step

- determine what tools can be available by Oct 1, 2013
- prioritize our development?

---

## Recap of Bereiter's keynote at KBSI2012

- Collaboration: interactions between individuals, between goals, ideas, and strategies.
- Quality of dialogue: assess whether the discussion is making progress or even whether it is on topic; track good things emerging from a good dialogue.
- New ideas, insights, discoveries, and inventions: not always attributable to individuals; low occurrence. 
- Growth in active vocabulary: change in actual use of domain vocabulary; the entry of new terms into classroom discourse.

---

## Recap of Bereiter's keynote at KBSI2012 (cont'd)

- Emergence and prevalence of naive conceptions or misconceptions: detect signs of concept learning going awry and map the spread or extinction of misconceptions. 
- Morale, socio-cognitive norms, collective cognitive responsibility, civility and other group-level virtues: higher-level evaluation is required. 

---

## Opening up for discussion



